description = 'jmsc-entity'

bootJar {
	enabled = false
}

jar {
	enabled = true
}

dependencies {
	implementation project(':jmsc-config')
	implementation project(':jmsc-enums')

	// ✅ Hibernate Types (updated for Hibernate 6)
	implementation 'com.vladmihalcea:hibernate-types-60:2.21.1'

	// ✅ JPA API
	implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'

	// ✅ Validation (if using annotations like @NotNull)
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
}